import { z } from "zod";

const envSchema = z.object({
 NODE_ENV: z.enum([
   "development",
   "test",
   "production"
 ]),

 NEXT_PUBLIC_APP_NAME: z.string().default("Sidra"),

 NEXT_PUBLIC_APP_URL: z.string().url(),

 NEXT_PUBLIC_APP_ENV: z.string(),

 NEXT_PUBLIC_FIREBASE_API_KEY: z.string(),

 NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: z.string(),

 NEXT_PUBLIC_FIREBASE_PROJECT_ID: z.string(),

 NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: z.string(),

 NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: z.string(),

 NEXT_PUBLIC_FIREBASE_APP_ID: z.string(),

 NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: z.string().optional(),

  FUNCTIONS_REGION: z.string().default("asia-south1")
});

export const env = envSchema.parse({
 NODE_ENV: process.env.NODE_ENV,

 NEXT_PUBLIC_APP_NAME:
  process.env.NEXT_PUBLIC_APP_NAME,

 NEXT_PUBLIC_APP_URL:
  process.env.NEXT_PUBLIC_APP_URL,

 NEXT_PUBLIC_APP_ENV:
  process.env.NEXT_PUBLIC_APP_ENV,

 NEXT_PUBLIC_FIREBASE_API_KEY:
  process.env.NEXT_PUBLIC_FIREBASE_API_KEY,

 NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:
  process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,

 NEXT_PUBLIC_FIREBASE_PROJECT_ID:
  process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,

 NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:
  process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,

 NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:
  process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,

 NEXT_PUBLIC_FIREBASE_APP_ID:
  process.env.NEXT_PUBLIC_FIREBASE_APP_ID,

 NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID:
  process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,

  FUNCTIONS_REGION:
    process.env.FUNCTIONS_REGION
});
